language: ruby
rvm:
  - 1.9.2
  - 2.0.0
  - rbx-19mode
  - 1.9.3

matrix:
  allow_failures:
    - rvm: rbx-19mode

services:
  - redis

script:
- bundle exec rake clean test
- bundle exec rspec specs

notifications:
  email:
    - james@jamesrgifford.com
    - scott@artsicle.com

gemfile:
  - gemfiles/rails3.gemfile
  - gemfiles/rails3_1.gemfile
  - gemfiles/rails3_2.gemfile


